name: Z3 Trace Log Generator

on:
  push:
    branches: [ "main" ]
    # only triggers job when smt2 files are changed (added/removed/modified) in a push
    paths:
      - '**/*.smt2'

  # job can also be triggered manually on GitHub
  workflow_dispatch:

jobs:
  generate_log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # this copies the whole repository
        with:
          fetch-depth: 0 # needed, see GitHub Action "Changed Files"

      - name: Install Z3
        uses: pavpanchekha/setup-z3@v1.3 # see GitHub Action "Install Z3"
        with:
          version: '4.12.2'

      # this fetches all changed (added/modified) smt2 files in the repository 
      - name: Fetch changed smt2 files
        id: changed-smt2-files
        uses: tj-actions/changed-files@v38.2.0 # see GitHub Action "Changed Files"
        with: 
          files_yaml: |
            smt:
              - '**/*.smt2'

      - name: Run Z3 solver on changed smt2 files and compress 
        id: run_z3_and_upload
        run: |
          mkdir logs
          for file in ${{ steps.changed-smt2-files.outputs.smt_all_changed_files }}; do
            echo "Processing $file"
            # Get the filename without extension
            base_name=$(basename "${file%.*}")
            # Run Z3 solver for $file
            z3 trace=true proof=true trace-file-name=${base_name}.log ./$file
            # Compress the file and save it to logs directory
            gzip -c ${base_name}.log > logs/${base_name}.log.gz
            echo "Compressed $file and saved to $logs/${base_name}.log.gz"
          done
          echo "::set-output name=logs_path::$(realpath logs)"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: z3_trace_logs
          path: ${{ steps.run_z3_and_upload.outputs.logs_path }}