name: Z3 Trace Log Generator

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.smt2'

  workflow_dispatch:

jobs:
  generate_log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Z3
        # uses: pavpanchekha/setup-z3@1.2.2
        uses: pavpanchekha/setup-z3@v1.3
        with:
          version: '4.12.2'
          # version: "4.8.7"

      - name: Fetch Changed smt2 Files
        id: changed-smt2-files
        uses: tj-actions/changed-files@v38.2.0
        with: 
          files_yaml: |
            smt:
              - '**/*.smt2'

      - name: Run Z3 Solver On Changed smt2 Files 
        id: run_z3_and_upload
        run: |
          mkdir logs
          for file in ${{ steps.changed-smt2-files.outputs.smt_all_changed_files }}; do
            echo "Processing $file"
            # Get the filename without extension
            base_name=$(basename "${file%.*}")
            # Run Z3 solver for $file
            z3 trace=true proof=true trace-file-name=${base_name}.log ./$file
            # Compress the file and save it to logs directory
            gzip -c ${base_name}.log > logs/${base_name}.log.gz
            echo "Compressed $file and saved to $logs/${base_name}.log.gz"
          done
          echo "::set-output name=logs_path::$(realpath logs)"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: z3_trace_logs
          path: ${{ steps.run_z3_and_upload.outputs.logs_path }}